### ISSUE TITLE
(Request) Upload New Sound Scripts when Noise Update Port releases

### ISSUE THREAD

**Issue by burnedpopcorn** [D-Official/PizzaTowerSwitch-FMOD#33]
I have made serveral PT ports to the Web Browser, my main one being the Noise Update Web Port.
One problem with my web ports is that the base game uses FMOD (something you clearly know about), and FMOD doesn't support WASM builds, so can you update and upload the sound scripts when your Noise Update port drops?

thanks in advance

(also I managed to decompile your latest release, so tell me if you want me to private it i guess, because its currently public)

:)

**Comment by notChocoMilk** [comment]
omg wait, i actually played your pizza tower and sonic mania ports a while back, that's cool

**Comment by burnedpopcorn** [comment]
Thanks, I'm still working on some other ports rn, so check them out when you can

**Comment by Dededeez** [comment]
D has said that they will release their GML replacement of FMOD here #30, so you probably just need to wait until SR 6 is finished for that.

**Comment by D-Official** [comment]
I will definitely be posting the rewritten script when SR 6 is out, which is VERY soon. I'll warn you though, and I should've probably mentioned this somewhere, the new script requires a minimum version of 2023.2, because of the audio looping functions. I'll close this issue once the update and the script is out.

On your decompilation, I don't mind the code being out there. The reason I didn't do it myself is that I didn't want to clean it up, and also releasing source code stripped of PT assets is annoying to set up.

**Comment by burnedpopcorn** [comment]
also, I know I might be asking for a bit much, but can you send me the SR 6 source code when you are finished?
It would just be faster to use that instead of having to manually do it myself (plus decompiling is never completely accurate)

If you want, you can send it to me under any conditions, I don't mind
I understand if you don't want to, but thanks in advance

**Comment by D-Official** [comment]
I'm not planning to publish the source myself. Thank you for understanding.

**Comment by burnedpopcorn** [comment]
no worries, thanks anyways

**Comment by D-Official** [comment]
https://github.com/D-Official/PizzaTowerSwitch-FMOD/blob/main/fmod.gml
