### ISSUE TITLE
will you ever consider publishing the port's source code the same way you publish new SRs in github?

### ISSUE THREAD

**Issue by lucasdaweb95** [D-Official/PizzaTowerSwitch-FMOD#9]

**Comment by D-Official** [comment]
I have considered it but I most likely won't do it for 2 reasons:

1. Most of it is identical to Pizza Tower's source code, except most notably for the FMOD portion which also could actually be very useful to others which is why I made it public

2. If anyone is interested regardless, for stuff like optimizations or the new menus, the port is compiled in VM mode, which means [UndertaleModTool](https://github.com/krzys-h/UndertaleModTool) or [DogScepter](https://github.com/colinator27/DogScepter) can provide very accurate and high quality decompiled GML output. All you would need to do is unpack the NSP to get out the game.win file, which those programs operate on.
